import type { ConfigContext, ExpoConfig } from 'expo/config';

/**
 * Dynamic app config.
 *
 * Expo loads `app.json` first and passes it in as `config`; this function
 * extends it. Keep static values in `app.json` and use this file only for
 * values that vary by environment or need to be computed.
 *
 * Native projects are generated by Continuous Native Generation, so native
 * behavior (bundle identifier, Android package, plugins) is configured here and
 * in `app.json`, never by hand-editing ios/ or android/.
 */

// Bundle identifier / Android package placeholders. Override per build/channel
// via env (for example a `.dev` or `.preview` suffix) without touching source.
const BUNDLE_IDENTIFIER = process.env.EXPO_PUBLIC_IOS_BUNDLE_IDENTIFIER ?? 'com.masari.app';
const ANDROID_PACKAGE = process.env.EXPO_PUBLIC_ANDROID_PACKAGE ?? 'com.masari.app';

// The deep-link scheme Auth0 uses for the login/logout callback. It must match
// the app's URL scheme (app.json `scheme`) and the Allowed Callback/Logout URLs
// configured on the Auth0 application. Keep it in sync with `scheme` in app.json.
const AUTH0_CUSTOM_SCHEME = 'masari';

export default ({ config }: ConfigContext): ExpoConfig => {
  const basePlugins = config.plugins ?? [];
  const withDevClient = basePlugins.includes('expo-dev-client')
    ? basePlugins
    : [...basePlugins, 'expo-dev-client'];

  // The react-native-auth0 config plugin wires the native deep-link handling for
  // Auth0's web-auth callback. It needs the Auth0 domain at build time (it writes
  // native manifest/Info.plist entries), so it is read from the build-time env
  // here rather than from src/lib/config.ts, which resolves at runtime. The
  // clientId is a runtime prop on <AuthProvider> (see src/lib/auth0.ts), not a
  // plugin option. CNG regenerates native projects, so this must be configured
  // here, never by hand-editing ios/ or android/.
  const auth0Domain = process.env.EXPO_PUBLIC_AUTH0_DOMAIN;
  const hasAuth0Plugin = withDevClient.some(
    (p) => p === 'react-native-auth0' || (Array.isArray(p) && p[0] === 'react-native-auth0'),
  );
  const auth0Plugin: NonNullable<ExpoConfig['plugins']>[number] = [
    'react-native-auth0',
    { domain: auth0Domain, customScheme: AUTH0_CUSTOM_SCHEME },
  ];
  const withAuth0 =
    hasAuth0Plugin || !auth0Domain ? withDevClient : [...withDevClient, auth0Plugin];

  // expo-web-browser opens the legal links (Privacy, Terms) in an in-app system
  // browser (SFSafariViewController / Chrome Custom Tabs). Its config plugin has
  // no required options; add it once. CNG regenerates native projects, so it is
  // configured here, never by hand-editing ios/ or android/.
  const hasWebBrowserPlugin = withAuth0.some(
    (p) => p === 'expo-web-browser' || (Array.isArray(p) && p[0] === 'expo-web-browser'),
  );
  const withWebBrowser: ExpoConfig['plugins'] = hasWebBrowserPlugin
    ? withAuth0
    : [...withAuth0, 'expo-web-browser'];

  // The @sentry/react-native Expo config plugin wires native crash capture and,
  // during EAS builds, source-map/debug-symbol upload. It needs no options here;
  // the DSN is supplied at runtime by Sentry.init (src/lib/sentry.ts) and the
  // upload auth token comes from the SENTRY_AUTH_TOKEN build-env variable. CNG
  // regenerates native projects, so this is configured here, never by hand.
  const hasSentryPlugin = withWebBrowser.some(
    (p) =>
      p === '@sentry/react-native/expo' ||
      (Array.isArray(p) && p[0] === '@sentry/react-native/expo'),
  );
  const withSentry: NonNullable<ExpoConfig['plugins']> = hasSentryPlugin
    ? withWebBrowser
    : [...withWebBrowser, '@sentry/react-native/expo'];

  // Apps built with the iOS 27 SDK (Xcode 27) crash at launch unless they adopt
  // the UIScene lifecycle, and Expo SDK 57 does not generate it yet. This local
  // plugin adds the scene manifest and SceneDelegate. Remove it once Expo ships
  // official support (https://github.com/expo/expo/issues/46663).
  const SCENE_PLUGIN = './plugins/with-ios-scene-delegate.js';
  const hasScenePlugin = withSentry.some(
    (p) => p === SCENE_PLUGIN || (Array.isArray(p) && p[0] === SCENE_PLUGIN),
  );
  const plugins: ExpoConfig['plugins'] = hasScenePlugin
    ? withSentry
    : [...withSentry, SCENE_PLUGIN];

  return {
    ...config,
    // `name` and `slug` are required by the ExpoConfig type; they always come
    // from app.json but TypeScript cannot prove that, so assert them.
    name: config.name ?? 'Masari',
    slug: config.slug ?? 'masariapp',
    ios: {
      ...config.ios,
      bundleIdentifier: BUNDLE_IDENTIFIER,
    },
    android: {
      ...config.android,
      package: ANDROID_PACKAGE,
    },
    plugins,
  };
};
