-- Generated by scripts/sync-catalog.ts from content/lessons/*.json (requirement 1.4).
-- DO NOT EDIT BY HAND. Re-run `npm run sync:catalog` after changing lesson content.
-- Seeds lessons_catalog and feature_unlock_rules
-- (supabase/migrations/20250104000001_learning_tables.sql).

insert into public.lessons_catalog
  (lesson_id, unit, sort_order, kind, xp_base, pass_score, prerequisite_lesson_id)
values
  ('L0', 0, 0, 'placement', 0, 0, NULL),
  ('L1.1', 1, 1, 'lesson', 10, 60, 'L0'),
  ('L1.2', 1, 2, 'lesson', 10, 60, 'L1.1'),
  ('L1.3', 1, 3, 'lesson', 10, 60, 'L1.2'),
  ('L1.4', 1, 4, 'lesson', 15, 60, 'L1.3'),
  ('L1.5', 1, 5, 'lesson', 15, 60, 'L1.4'),
  ('B1', 1, 6, 'boss', 30, 70, 'L1.5'),
  ('L2.1', 2, 1, 'lesson', 10, 60, 'B1')
on conflict (lesson_id) do update set
  unit = excluded.unit,
  sort_order = excluded.sort_order,
  kind = excluded.kind,
  xp_base = excluded.xp_base,
  pass_score = excluded.pass_score,
  prerequisite_lesson_id = excluded.prerequisite_lesson_id;

insert into public.feature_unlock_rules
  (feature_key, lesson_id, description)
values
  ('paper_account', 'L0', NULL),
  ('explore', 'L1.1', NULL),
  ('watchlist', 'L1.2', NULL),
  ('price_tickers', 'L1.2', NULL),
  ('stock_detail', 'L1.3', NULL),
  ('market_buy', 'L1.4', NULL),
  ('portfolio', 'L1.4', NULL),
  ('pre_trade_rationale', 'L1.4', NULL),
  ('market_sell', 'L1.5', NULL),
  ('pnl_display', 'L1.5', NULL),
  ('trade_history', 'L1.5', NULL),
  ('post_trade_reflection', 'L1.5', NULL),
  ('daily_briefing', 'B1', NULL),
  ('rank_rookie', 'B1', NULL),
  ('chart_time_ranges', 'L2.1', NULL),
  ('trade_markers', 'L2.1', NULL)
on conflict (feature_key) do update set
  lesson_id = excluded.lesson_id,
  description = excluded.description;
