-- Onboarding-revamp migration: relax the username format and add a shared
-- server-side username validator.
--
-- Context: usernames were previously auto-generated by the client in the shape
-- `adjective-animal-number` and enforced by a CHECK on profiles.username
-- (^[a-z]{3,12}-[a-z]{3,12}-[0-9]{2,4}$) plus the auto-named unique constraint
-- `profiles_username_key`. The app now lets a user pick their OWN username, so:
--
--   1. Relax the format to a broad, friendly shape: letters, numbers, underscore
--      and hyphen, 3-20 chars (^[a-zA-Z0-9_-]{3,20}$). Every previously
--      generated name still satisfies this (lowercase + hyphen + digits, and the
--      longest possible generated name is 19 chars), so no existing row is
--      invalidated.
--   2. Make uniqueness CASE-INSENSITIVE so `Otter` and `otter` cannot both
--      exist. We replace the plain unique constraint with a unique index on
--      lower(username). create_profile is updated (in a later migration) to map
--      a clash on THIS index to `username_taken`.
--   3. Add public.username_allowed(text): one source of truth for "is this
--      username acceptable" (format + a reviewed blocklist of obviously
--      unsuitable words). Both is_username_available and create_profile call it
--      so the client-side filter cannot be bypassed by hitting the API directly.
--
-- The client mirrors username_allowed in src/features/auth/username-filter.ts;
-- keep the two in sync when editing the pattern or the blocklist.

-- ---------------------------------------------------------------------------
-- 1 + 2. Relax the CHECK and switch to case-insensitive uniqueness.
-- ---------------------------------------------------------------------------

-- Drop the old format CHECK (auto-named profiles_username_check) and add the
-- relaxed one. Use the known default constraint name; it was created inline on
-- the table in 20250103000002_identity_and_consent.sql.
alter table public.profiles
  drop constraint if exists profiles_username_check;

alter table public.profiles
  add constraint profiles_username_check
  check (username ~ '^[a-zA-Z0-9_-]{3,20}$');

-- Replace the case-sensitive unique constraint with a case-insensitive unique
-- index so usernames that differ only in case are treated as the same name.
alter table public.profiles
  drop constraint if exists profiles_username_key;

create unique index if not exists profiles_username_lower_key
  on public.profiles (lower(username));

-- ---------------------------------------------------------------------------
-- 3. Shared validator: format + blocklist. Immutable + no table reads so it is
-- cheap to call from the availability check and from create_profile.
-- ---------------------------------------------------------------------------
--
-- Blocklist note: this is a small, reviewed set of obviously unsuitable terms
-- for a teen audience (slurs/profanity/sexual terms), matched case-insensitively
-- as substrings so simple obfuscations (leet-free) are still caught. It is a
-- pragmatic filter, not an exhaustive moderation system. Keep it in sync with
-- the client list in src/features/auth/username-filter.ts. The words are kept as
-- lowercase fragments; `_blocked` is checked with a case-insensitive LIKE.

create or replace function public.username_allowed(p_username text)
returns boolean
language plpgsql immutable set search_path = public as $$
declare
  v_norm text;
  v_fragment text;
  v_blocklist text[] := array[
    'fuck', 'shit', 'cunt', 'bitch', 'bastard', 'dick', 'piss',
    'nigger', 'nigga', 'faggot', 'fag', 'retard', 'whore', 'slut',
    'rape', 'nazi', 'hitler', 'kkk', 'pedo', 'porn', 'sex', 'cum',
    'penis', 'vagina', 'boob', 'tits', 'anus', 'anal'
  ];
begin
  if p_username is null then
    return false;
  end if;

  -- Format gate: must match the relaxed pattern the CHECK enforces.
  if p_username !~ '^[a-zA-Z0-9_-]{3,20}$' then
    return false;
  end if;

  -- Blocklist gate: reject if any blocked fragment appears (case-insensitive).
  v_norm := lower(p_username);
  foreach v_fragment in array v_blocklist loop
    if position(v_fragment in v_norm) > 0 then
      return false;
    end if;
  end loop;

  return true;
end $$;

-- The availability check and create_profile call this; it reads no tables and
-- leaks nothing, so expose it to the authenticated client role.
grant execute on function public.username_allowed(text) to authenticated;
